name: Docker Image CI

on:
  push:
    branches: [ "prometheus" ]

env:
  REGISTRY_IMAGE: ghcr.io/xingoxu/intel-gpu-exporter

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        # Platforms to install (e.g. arm64,riscv64,arm)
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile-prometheus
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGISTRY_IMAGE }}:prometheus
          
